# Generated by Django 2.2 on 2020-11-25 04:31

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterFaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_features_names', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
